name: Waka Readme

on:
  schedule:
    # Runs at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: True
          SHOW_COMMIT: True
          Show_OS: True
          SHOW_LOC_CHART: False
          SHOW_PROFILE_VIEWS: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_PROJECTS: False
          SHOW_TIMEZONE: False
          SHOW_EDITORS: True
          SHOW_SHORT_INFO: False
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
